---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: testchatbot1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testchatbot1 
  name: testchatbot1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi