apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testchatbot1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testchatbot1 
  name: testchatbot1
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testchatbot1 
    weight: 100 
  wildcardPolicy: None
