apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testchatbot1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testchatbot1 
  name: testchatbot1
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: testchatbot1 
